const labFields=[['contact-map','Contact map'],['incident-one','Detailed incident response 1'],['incident-two','Detailed incident response 2'],['incident-rapid','Four rapid incident responses'],['desk-sequence','CO-OP Desk daily sequence'],['desk-problem','Technology problem recovery'],['hours-audit','Hours audit and calculations'],['hours-errors','Hours corrections'],['structured-answer','Structured daily answer'],['reflection','Short reflection'],['delay-message','Delay message and notifications'],['boundary-messages','Supervisor and privacy responses'],['friday-audit','Friday review and sign-off'],['launch-verdict','Launch self-status']];
const labMeter=document.getElementById('lab-meter'),labCount=document.getElementById('lab-count'),labStatus=document.getElementById('lab-status');
const updateLab=()=>{const started=labFields.filter(([id])=>document.getElementById(id).value.trim()).length;labMeter.max=labFields.length;labMeter.value=started;labCount.textContent=`${started} of ${labFields.length} responses started`;labFields.forEach(([id])=>document.getElementById(id).classList.toggle('started',Boolean(document.getElementById(id).value.trim())))};
const labExport=()=>`DAY 6 — FIRST-WEEK OPERATIONS LAB\nFictional practice unless clearly identified as a personal plan\n\n${labFields.map(([id,label])=>`${label}\n${document.getElementById(id).value.trim()||'[not completed]'}`).join('\n\n')}`;
labFields.forEach(([id])=>document.getElementById(id).addEventListener('input',updateLab));
document.getElementById('check-lab').addEventListener('click',()=>{const missing=labFields.filter(([id])=>!document.getElementById(id).value.trim());labStatus.textContent=missing.length?`${missing.length} response(s) are blank. Complete them before turning in.`:'All 14 responses contain text. Use the quality checklist, then download and submit.';if(missing.length)document.getElementById(missing[0][0]).focus()});
document.getElementById('download-lab').addEventListener('click',()=>{const url=URL.createObjectURL(new Blob([labExport()],{type:'text/plain;charset=utf-8'}));const link=document.createElement('a');link.href=url;link.download='Day_6_First_Week_Operations_Lab.txt';document.body.appendChild(link);link.click();link.remove();setTimeout(()=>URL.revokeObjectURL(url),1000);labStatus.textContent='Download requested. Check that the file saved, then attach it in Classroom.'});
document.getElementById('prepare-lab-copy').addEventListener('click',()=>{const output=document.getElementById('lab-copy');output.value=labExport();output.focus();output.select()});
document.getElementById('operations-form').addEventListener('submit',event=>event.preventDefault());updateLab();
