(()=>{'use strict';
const mode=document.body.dataset.game,game=window.SAFETY_GAMES[mode],key='bhs-safety-v1-'+mode,$=id=>document.getElementById(id);
const esc=s=>String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const fresh=()=>({index:0,history:game.items.map(()=>[]),answers:['',''],name:'',finished:false,started:new Date().toISOString()});
let state=fresh();try{const saved=JSON.parse(sessionStorage.getItem(key));if(saved&&saved.history?.length===game.items.length&&Number.isInteger(saved.index)&&saved.index>=0&&saved.index<=game.items.length)state=saved;}catch(e){}
const save=()=>{try{sessionStorage.setItem(key,JSON.stringify(state));}catch(e){$('save-note').textContent='This browser cannot save progress. Keep this page open and download before leaving.';}};
const same=(a,b)=>a.length===b.length&&a.every(x=>b.includes(x));
const resolved=i=>state.history[i].length>0&&same(state.history[i].at(-1),game.items[i].correct);
const total=()=>state.history.filter((h,i)=>h.length&&same(h[0],game.items[i].correct)).length;
function render(){
 const n=game.items.length,count=game.items.filter((_,i)=>resolved(i)).length;
 $('progress').max=n;$('progress').value=count;$('progress-label').textContent=count+' of '+n+' decisions resolved';
 const stages=[...new Set(game.items.map(q=>q.stage))];$('stages').innerHTML=stages.map(stage=>{const items=game.items.map((q,i)=>q.stage===stage?i:-1).filter(i=>i>=0);const done=items.every(resolved);return '<span class="stage '+(done?'done':'')+'">'+(done?'✓ ':'')+esc(stage)+'</span>';}).join('');
 if(state.index>=n){$('challenge').hidden=true;$('reflection').hidden=state.finished;$('finish').hidden=!state.finished;if(state.finished)showSummary();return;}
 $('challenge').hidden=false;$('reflection').hidden=true;$('finish').hidden=true;
 const q=game.items[state.index];const history=state.history[state.index],done=resolved(state.index),last=history.at(-1)||[];
 $('challenge').innerHTML='<div class="eyebrow">Decision '+(state.index+1)+' · '+esc(q.stage)+'</div><h2 tabindex="-1" id="question-title">'+esc(q.title)+'</h2><p>'+esc(q.story)+'</p><form id="decision-form"><fieldset><legend>'+(q.multi?'Select '+q.correct.length+' answers.':'Choose your response.')+'</legend>'+q.options.map((opt,i)=>'<label class="option"><input type="'+(q.multi?'checkbox':'radio')+'" name="choice" value="'+i+'" '+(last.includes(i)?'checked ':'')+(done?'disabled':'')+'><span>'+esc(opt)+'</span></label>').join('')+'</fieldset><button class="button" type="submit" '+(done?'disabled':'')+'>Check decision</button></form><div id="feedback" class="feedback" role="status" '+(history.length?'':'hidden')+'>'+(history.length?(done?'Decision resolved. ':'Take another look. ')+esc(q.why):'')+'</div><button id="next" class="button" '+(done?'':'hidden')+'>Next '+(state.index===n-1?'— explain your thinking':'decision →')+'</button>';
 $('decision-form').addEventListener('submit',e=>{e.preventDefault();const choices=[...$('decision-form').querySelectorAll('input:checked')].map(el=>Number(el.value));if(!choices.length){$('feedback').hidden=false;$('feedback').textContent='Choose a response first.';return;}state.history[state.index].push(choices);save();render();});
 $('next').addEventListener('click',()=>{if(!resolved(state.index))return;state.index++;save();render();(state.index<n?$('question-title'):$('reflection')).scrollIntoView({behavior:'smooth',block:'start'});if(state.index<n)$('question-title').focus({preventScroll:true});else $('response-0').focus({preventScroll:true});});
}
$('prompts').innerHTML=game.prompts.map((p,i)=>'<label for="response-'+i+'">'+esc(p)+'</label><textarea id="response-'+i+'" rows="4" maxlength="700" required></textarea>').join('');
game.prompts.forEach((_,i)=>{const field=$('response-'+i);field.value=state.answers[i]||'';field.addEventListener('input',()=>{field.setCustomValidity('');state.answers[i]=field.value;state.finished=false;save();});});$('student-name').value=state.name||'';$('student-name').addEventListener('input',()=>{state.name=$('student-name').value;state.finished=false;save();});
$('reflection-form').addEventListener('submit',e=>{e.preventDefault();if(!game.items.every((_,i)=>resolved(i)))return;for(let i=0;i<game.prompts.length;i++){const field=$('response-'+i);if(field.value.trim().split(/\s+/).filter(Boolean).length<10){field.setCustomValidity('Use at least 10 words to explain your next steps. Your teacher will review the explanation.');field.reportValidity();return;}}if(!state.name.trim()){ $('student-name').focus();return;}state.finished=true;state.completed=new Date().toISOString();save();render();$('finish').scrollIntoView({behavior:'smooth'});});
function showSummary(){$('summary').textContent=state.name+' — all '+game.items.length+' decisions corrected/completed. First-choice matches: '+total()+'/'+game.items.length+'. Your teacher can review retries and explanations in the record. This is not a grade.';}
$('edit-reflection').addEventListener('click',()=>{state.finished=false;save();render();$('response-0').focus();});
$('restart').addEventListener('click',()=>{if(!confirm('Clear this tab’s answers and start again? Download any completed record first.'))return;state=fresh();save();game.prompts.forEach((_,i)=>$('response-'+i).value='');$('student-name').value='';render();});
function recordRows(){const rows=[['Brooklin High School',32],['CLASSROOM PRACTICE COMPLETION RECORD',26],[game.title,28],['Student: '+state.name,22],['Completed: '+new Date(state.completed).toLocaleString('en-CA'),20],['All '+game.items.length+' decisions resolved after feedback. First-choice matches: '+total()+'/'+game.items.length+'. Ungraded.',22],['This student-generated record is not an official training certificate, verification of independent performance, or placement clearance.',20],['Teacher review: check explanations and discuss missed first choices. A correct retry alone does not establish understanding.',20],['Decision history',26]];
 game.items.forEach((q,i)=>{const h=state.history[i];rows.push([(i+1)+'. '+q.title,23],[q.story,19],['First choice: '+h[0].map(j=>q.options[j]).join(' | '),19],['Attempts: '+h.length+'; '+(same(h[0],q.correct)?'matched on first choice':'corrected after feedback')+'.',19]);if(h.length>1)rows.push(['Retry choices: '+h.slice(1).map((a,j)=>(j+2)+': '+a.map(k=>q.options[k]).join(' | ')).join('; '),18]);rows.push(['Final response: '+q.correct.map(j=>q.options[j]).join(' | '),19]);});
 rows.push(['Written explanations — teacher review needed',26]);game.prompts.forEach((q,i)=>rows.push([q,22],[state.answers[i],21]));rows.push(['Teacher follow-up (not assessed by this website): Ask the student to explain one corrected decision in a new situation. Confirm official training records, site orientation and task-specific instruction separately.',20]);return rows;}
// Draw Unicode text onto pages, then embed those pages into a small, locally generated PDF.
function makePdf(rows){const pages=[];let canvas,ctx,y;const width=1275,height=1650,margin=85;
 function page(){canvas=document.createElement('canvas');canvas.width=width;canvas.height=height;ctx=canvas.getContext('2d');ctx.fillStyle='#fff';ctx.fillRect(0,0,width,height);ctx.fillStyle='#00677c';ctx.fillRect(0,0,width,24);y=75;pages.push(canvas);}
 page();for(const [text,size] of rows){if(size>=23&&y>height-230)page();ctx.font=(size>=23?'bold ':'')+size+'px Arial';const lines=[];let line='';for(const word of String(text).split(/\s+/)){if(ctx.measureText(line+(line?' ':'')+word).width>width-2*margin&&line){lines.push(line);line='';}if(ctx.measureText(word).width>width-2*margin){for(const ch of word){if(ctx.measureText(line+ch).width>width-2*margin){lines.push(line);line='';}line+=ch;}}else line+=(line?' ':'')+word;}if(line)lines.push(line);for(const l of lines){if(y+size*1.5>height-90){page();ctx.font=(size>=23?'bold ':'')+size+'px Arial';}ctx.fillStyle=size>=23?'#00677c':'#202c32';ctx.fillText(l,margin,y+size);y+=size*1.45;}y+=18;}
 pages.forEach((c,i)=>{const x=c.getContext('2d');x.font='18px Arial';x.fillStyle='#52646b';x.fillText('Brooklin Co-op | Classroom practice | Page '+(i+1)+' of '+pages.length,margin,height-40);});
 const enc=new TextEncoder(),chunks=[],offsets=[0];let length=0;const add=v=>{const b=typeof v==='string'?enc.encode(v):v;chunks.push(b);length+=b.length;};const obj=(id,body)=>{offsets[id]=length;add(id+' 0 obj\n');add(body);add('\nendobj\n');};add('%PDF-1.4\n');obj(1,'<< /Type /Catalog /Pages 2 0 R >>');obj(2,'<< /Type /Pages /Count '+pages.length+' /Kids ['+pages.map((_,i)=>(3+i*3)+' 0 R').join(' ')+'] >>');pages.forEach((c,i)=>{const id=3+i*3,raw=atob(c.toDataURL('image/jpeg',.9).split(',')[1]),bytes=Uint8Array.from(raw,ch=>ch.charCodeAt(0));obj(id,'<< /Type /Page /Parent 2 0 R /MediaBox [0 0 612 792] /Resources << /XObject << /Img '+(id+1)+' 0 R >> >> /Contents '+(id+2)+' 0 R >>');offsets[id+1]=length;add((id+1)+' 0 obj\n<< /Type /XObject /Subtype /Image /Width '+width+' /Height '+height+' /ColorSpace /DeviceRGB /BitsPerComponent 8 /Filter /DCTDecode /Length '+bytes.length+' >>\nstream\n');add(bytes);add('\nendstream\nendobj\n');const stream='q 612 0 0 792 0 0 cm /Img Do Q';obj(id+2,'<< /Length '+stream.length+' >>\nstream\n'+stream+'\nendstream');});const xref=length,count=3+pages.length*3;add('xref\n0 '+count+'\n0000000000 65535 f \n');for(let i=1;i<count;i++)add(String(offsets[i]).padStart(10,'0')+' 00000 n \n');add('trailer\n<< /Size '+count+' /Root 1 0 R >>\nstartxref\n'+xref+'\n%%EOF');return new Blob(chunks,{type:'application/pdf'});}
function download(blob,name){const url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download=name;document.body.appendChild(a);a.click();a.remove();setTimeout(()=>URL.revokeObjectURL(url),30000);}
$('download').addEventListener('click',()=>{if(!state.finished||!game.items.every((_,i)=>resolved(i)))return;try{download(makePdf(recordRows()),'Day_4_'+mode+'_Completion.pdf');$('download-status').textContent='Download requested. Open the saved PDF, then upload it to '+game.title+' in Classroom.';}catch(e){$('download-status').textContent='PDF could not be generated. Use Download text record instead, or tell your teacher.';}});
const textButton=document.createElement('button');textButton.type='button';textButton.textContent='Download accessible text record';textButton.addEventListener('click',()=>{if(state.finished)download(new Blob([recordRows().map(r=>r[0]).join('\n\n')],{type:'text/plain;charset=utf-8'}),'Day_4_'+mode+'_Completion.txt');});$('download').after(textButton);
render();
})();
