(()=>{const script=document.createElement('script');script.src='/brooklin-coop/typed-input.js';script.async=false;document.head.appendChild(script);})();
const missionFields=[['route-choice','Mission route and evidence'],['intel-board','Orientation intel board'],['priority-questions','Priority questions'],['travel-puzzle','Travel puzzle'],['travel-plan','Travel plan'],['delay-message','Delay message'],['gear-sort','Pack, confirm or pause sort'],['missing-item','Added item'],['decision-one','Decision scenario 1'],['decision-two','Decision scenario 2'],['rapid-decisions','Rapid decisions'],['goal-draft','Learning goal'],['first-day-script','First-day introduction'],['readiness-verdict','Readiness self-status']];
const missionMeter=document.getElementById('mission-meter'),missionCount=document.getElementById('mission-count'),missionStatus=document.getElementById('mission-status');
const updateMission=()=>{const started=missionFields.filter(([id])=>document.getElementById(id).value.trim()).length;missionMeter.max=missionFields.length;missionMeter.value=started;missionCount.textContent=`${started} of ${missionFields.length} responses started`;missionFields.forEach(([id])=>document.getElementById(id).classList.toggle('started',Boolean(document.getElementById(id).value.trim())))};
const missionExport=()=>`DAY 5 — FIRST-DAY READINESS MISSION\nPlanning activity—not placement clearance\n\n${missionFields.map(([id,label])=>`${label}\n${document.getElementById(id).value.trim()||'[not completed]'}`).join('\n\n')}`;
missionFields.forEach(([id])=>document.getElementById(id).addEventListener('input',updateMission));
document.getElementById('check-mission').addEventListener('click',()=>{const missing=missionFields.filter(([id])=>!document.getElementById(id).value.trim());missionStatus.textContent=missing.length?`${missing.length} response(s) are blank. You may download a draft, but complete them before turning in.`:'All responses contain text. Use the checklist to review their quality, then download and submit.';if(missing.length)document.getElementById(missing[0][0]).focus()});
document.getElementById('download-mission').addEventListener('click',()=>{const url=URL.createObjectURL(new Blob([missionExport()],{type:'text/plain;charset=utf-8'}));const link=document.createElement('a');link.href=url;link.download='Day_5_First_Day_Readiness_Mission.txt';document.body.appendChild(link);link.click();link.remove();setTimeout(()=>URL.revokeObjectURL(url),1000);missionStatus.textContent='Download requested. Check that the file saved, then attach it in Classroom.'});
document.getElementById('prepare-mission-copy').addEventListener('click',()=>{const output=document.getElementById('mission-copy');output.value=missionExport();output.focus();output.select()});document.getElementById('mission-form').addEventListener('submit',event=>event.preventDefault());updateMission();
